version: "3"

services:
    frontend:
        build:
            context: ./frontend
        container_name: frontend
        restart: unless-stopped
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/node/frontend
            - /node/frontend/node_modules
        depends_on:
            - backend
        networks:
            - rest-network
        command: npm run dev
    backend:
        build:
            context: ./backend
        container_name: backend
        restart: unless-stopped
        env_file: .env
        environment:
            - MONGO_USERNAME=$MONGO_USERNAME
            - MONGO_PASSWORD=$MONGO_PASSWORD
            - MONGO_HOSTNAME=db
            - MONGO_PORT=$MONGO_PORT
            - MONGO_DB=$MONGO_DB
        ports:
            - "1337:1337"
        volumes:
            - ./backend:/node/backend
            - /node/backend/node_modules
        depends_on:
            - db
        networks:
            - db-network
            - rest-network
        command: npm start
    seeder:
        build:
            context: ./seeder
        image: pkosiec/mongo-seeding:3.3.0
        container_name: seeder
        env_file: .env
        environment:
            - DB_URI=mongodb://$MONGO_USERNAME:$MONGO_PASSWORD@$MONGO_HOSTNAME:$MONGO_PORT/$MONGO_DB?authSource=admin
            - DROP_DATABASE=true
            - SET_TIMESTAMPS=true
        volumes:
            - ./seeder/data/:/seeder/import-data/
        depends_on:
            - backend
        networks:
            - db-network

    db:
        image: mongo:4.1.8-xenial
        container_name: db
        restart: unless-stopped
        env_file: .env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
        ports:
            - "27017:27017"
        volumes:
            - dbdata:/data/db
        networks:
            - db-network

networks:
    db-network:
        driver: bridge
    rest-network:
        driver: bridge

volumes:
    dbdata:
