version: "3"

services:
    test-backend:
        build:
            context: ./backend
        container_name: test-backend
        restart: unless-stopped
        env_file: .env
        environment:
            - MONGO_USERNAME=$MONGO_USERNAME
            - MONGO_PASSWORD=$MONGO_PASSWORD
            - MONGO_HOSTNAME=db
            - MONGO_PORT=$MONGO_PORT
            - MONGO_DB=$MONGO_DB
        ports:
            - "1337:1337"
        volumes:
            - ./backend:/node/backend
            - /node/backend/node_modules
        depends_on:
            - seeder
        networks:
            - db-network
        command: npm run test
